### ISSUE TITLE
How does one run the test file?

### ISSUE THREAD

**Issue by technobly** [cscott/lzjb#1]
I must be missing something because I'm having a hard time running this:
https://github.com/cscott/lzjb/blob/master/test/IuppiterTest.js
I was getting errors that 'describe' is not defined.
Do I need to use Mocha for that?

I ended up rewriting it like this and everything works fine, but I'd sure like to know the right way ;-)

``` javascript
var lzjb = require('lzjb');
var fs = require('fs');

function test() {
    var s = "Hello World!!!Hello World!!!Hello World!!!Hello World!!!";
    for(var i = 0; i < 2; i++)
        s += s;
    s = new Buffer(s, 'utf8');

    var c = lzjb.compressFile(s);
    c = new Buffer(c);
    console.log("should be smaller when compressed, old: "+s.length+" vs. new: "+c.length);

    var d = lzjb.decompressFile(c);
    d = new Buffer(d);

    console.log('should decompress to the original string: '+ (d.toString('utf8') === s.toString('utf8')) );
    console.log("NEW: "+d.toString('utf8'));
    console.log("OLD: "+s.toString('utf8'));
}

test();
```

**Comment by cscott** [comment]
npm install; npm test

**Comment by technobly** [comment]
"npm install" gives me errors
"npm test" does nothing
"npm install test" seems to install something for testing.. but that describe() function is still not recognized.

any other ideas? thanks.

**Comment by technobly** [comment]
Got it working, except I like my rewrite better... since I can see numbers :)
"npm install -g mocha"
"mocha --reporter spec test.js"
http://i.imgur.com/88btVJ6.png
(although this looks prettier)
